### ISSUE TITLE
version和inputMapping通过${{}} 传入的表达式没有生效

### ISSUE THREAD

**Issue by huaxiexiexiexie** [qhy040404/Bugly-mapping-upload#2]
1、version通过上一步的${{ steps.versionReader.outputs.versionName }}传入，无效
2、inputMapping通过${{ github.workspace }}/apps/xxxxx//build/outputs/mapping/pgyerRelease/mapping.txt传入，实际读到的参数为/github/workspace/apps/xxxx/build/outputs/mapping/pgyerRelease/mapping.txt

**Comment by qhy040404** [comment]
1检查上一步输出
2请传入gradle导出的mapping文件夹，工作文件夹为git clone下来的目录，例如克隆到了`/github/workspace/apps/xxxx`, 则对应的`inputMapping`为`build/outputs/mapping/pgyerRelease`

**Comment by qhy040404** [comment]
1可以在action的log里面看现有参数以及报错
